Repository lenra-io/components-api, pull requests merged in 2022-08, with the labels that each got.

#111 feat: add context in components-api
  api/components/widget.schema.json
Labels: enhancement

#115 feat: Add mdx documentation
  .github/workflows/semantic_release.yml
  .releaserc.yml
  docs/.gitignore
  docs/package-lock.json
  docs/package.json
  docs/src/components/propertyTable.jsx
  docs/src/pages/button.mdx
Labels: documentation, enhancement

#118 fix: Documentation release
  .github/workflows/semantic_release.yml
  .releaserc.yml
  docs/package-lock.json
  docs/package.json
Labels: bug
